# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pthoto_url', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('car_groupId', models.IntegerField(max_length=100)),
                ('status', models.IntegerField(max_length=100)),
                ('deviceTpye', models.IntegerField(max_length=100)),
                ('buildId', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
