# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-02 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20190125_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='status',
            new_name='isPass',
        ),
    ]
